version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Brazil/East
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
    - 1.3.0-rc01
    - 1.4.0-alpha01
  - dependency-name: androidx.lifecycle:lifecycle-viewmodel-ktx
    versions:
    - 2.3.0
  - dependency-name: com.kezong:fat-aar
    versions:
    - 1.3.3
  - dependency-name: junit:junit
    versions:
    - 4.13.1
