version: 2.1
orbs:
  node: circleci/node@3.0.1

executors:
  mac_exe:
    macos:
      xcode: "11.4.1"

references:
  ## Workspace
  workspace: &workspace ~/workspace

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

commands:
  shell-script-command:
    description: "Testing command"
    steps:
      - run:
          name: Install Yarn
          command: yarn install
      - run: sh ./scripts/generate_new_version.sh

jobs:
  deploy-ocean-tokens:
    <<: *android_config
    steps:
      - checkout
      - shell-script-command

workflows:
  android-test-workflow:
    jobs:
      - deploy-ocean-tokens:
        filters:
          branches:
            only: DSO-33-ocean-ds-lib-gen-automation
