version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  android-test-job:
    executor:
      name: node/default
      tag: "10.4"
    steps:
      - checkout
       - run:
          name: First run
          command: sh ./scripts/generate_new_version.sh
workflows:
  android-test-workflow:
    jobs:
      - android-test-job:
        filters:
          branches:
            only: DSO-33-ocean-ds-lib-gen-automation
